
MAP_SIZE_X = 20
MAP_SIZE_Y = 14

TILE_SIZE = 32

GUI_UPPER = 0
GUI_RIGHT = 0

CAMERA_FOLLOW_PLAYER = False

WINDOW_FULLSCREEN = False
WINDOW_RESIZABLE = True

WINDOW_SIZE_X = GUI_RIGHT + MAP_SIZE_X * TILE_SIZE
WINDOW_SIZE_Y = GUI_UPPER + MAP_SIZE_Y * TILE_SIZE
